name: Grackle Server Scheduled Daily Deployment
run-name: Grackle Server Scheduled Daily Deployment
on:
  schedule:
  - cron: 0  3 * * *
  
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build script
        shell: bash
        run: ./server/build.sh
  deploy:
    name: deploy
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build script
        shell: bash
        run: ./server/build.sh
    
