name: Grackle Server Scheduled Daily Deployment
run-name: Grackle Server Scheduled Daily Deployment
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        
defaults:
  run:
    working-directory: /home/runner/work/Grackle/server
  
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run makefile
        shell: bash
        run: |
          pwd
          make all
  deploy:
    name: deploy
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build script
        shell: bash
        run: ./server/build.sh
    
