name: Grackle Server Scheduled Daily Deployment
run-name: Grackle Server Scheduled Daily Deployment
on:
  schedule:
  - cron: 0  3 * * *
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build application
        shell: bash
        run: ./server/build.sh
      - name: deploy application
        run: ./server/deploy.sh
